//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingUsingMVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public short StaffId { get; set; }
        public string StaffName { get; set; }
        public byte RoleId { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
